# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import os
import sys
import types
import _ctypes
import struct
import nt
import comtypes
import comtypes.server
import comtypes.server.inprocserver
import wave
import pathlib
import threading
import time
import typing
import pyaudio
import argparse
import configparser
import platform
import enum
import ntpath
import serial
import json
import json.JSONDecodeError
import re
import select
import pykob.VERSION
import traceback
import gpiozero
import datetime
import codecs
import urllib
import urllib.request
import tkinter
import tkinter.ttk
import serial.tools
import serial.tools.list_ports
import queue
import _socket
import io
import selectors
import errno
import array

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

